---
# tasks file for mysql

- name: Create mysql database
  mysql_db: 
     name: "{{ wp_mysql_db }}"
     state: present
     login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

- name: Create mysql user
  mysql_user:
     name: "{{ wp_mysql_user }}"
     password: "{{ wp_mysql_password }}"
     priv: "*.*:ALL"
     login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
